### PR TITLE
Update hello.py

### PR DESCRIPTION
**Pull request by Ctoic**
Hey Art3mis accept the change.

### CODE REVIEW

**Comment by Ctoic** [comment]
If you have any questions ask.

**Comment by Ctoic** [comment]
What will be the output?

**Comment by Art3mis-s** [comment]
> What will be the output?

One smiley face and one sad face at a time ?

**Comment by Ctoic** [comment]
Okay but when it will be happy and when it will be sad ?

**Comment by Ctoic** [comment]
Come up with a reason 😃

**Comment by Art3mis-s** [comment]
> Okay but when it will be happy and when it will be sad ?

so the code contains one nested FOR loop which the inner loop iterates over the numbers 0-9 and the outer 0-1, 
well, as u wrote there: if j % 2 == 0:
The "j % 2" calculates the remainder, and it checks whether the remainder divided by 2 is equal to 0, if it is, j is even, otherwise j is odd, so it means the code will print a smiley face when j is an even number and a sad face when it is an odd number. 


I hope my answer makes sense.

**Comment by Ctoic** [comment]
Exactly 💯  You can add more problems to this repository.

**Pull request merged**
